<a href="https://colab.research.google.com/github/Mahe7461/Angular/blob/main/Predict_user_purchase_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
data = pd.read_csv('/content/drive/MyDrive/psahkprod_orders_test.csv')
data.dropna(inplace=True)
data['invoice_date'] = pd.to_datetime(data['invoice_date'])
data['invoice_year'] = data['invoice_date'].dt.year
print(data)

# Sort the data by 'invoice_date' in ascending order
data.sort_values(by='invoice_date', inplace=True)

# Group data by 'id_customer' and aggregate total_paid as sum
cus_data= data.groupby(['id_customer','invoice_year'])['total_paid'].agg(np.sum)
df=cus_data.to_frame()
print(df)
df.to_csv('test.csv')
# X = dataset.iloc[:, :-1].values
# y = dataset.iloc[:, -1].values

       id_customer  total_paid invoice_date  invoice_year
0              780      726.00   2020-08-31          2020
1             1817     2781.00   2020-08-31          2020
2              210      166.83   2020-01-09          2020
3             1038     1209.00   2019-01-30          2019
4             1427      216.00   2016-03-15          2016
...            ...         ...          ...           ...
47337          590     2477.50   2023-08-09          2023
47338         1105      341.80   2023-08-09          2023
47339         1200      266.50   2023-08-09          2023
47340         1470      764.96   2023-08-09          2023
47341          269      486.20   2023-11-09          2023

[47342 rows x 4 columns]
                          total_paid
id_customer invoice_year            
0           2014              333.50
            2021            18256.52
            2022            22685.82
            2023            17810.10
1           2016             3670.50
...                

In [3]:
dataset = pd.read_csv('/content/test.csv')
dataset['total_paid']=dataset['total_paid'].astype(int)
dataset['id_customer']=dataset['id_customer'].astype(int)
print(dataset)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


      id_customer  invoice_year  total_paid
0               0          2014         333
1               0          2021       18256
2               0          2022       22685
3               0          2023       17810
4               1          2016        3670
...           ...           ...         ...
5252         6941          2023        1029
5253         6948          2023         475
5254         6950          2023         348
5255         6969          2023         413
5256         6994          2023         784

[5257 rows x 3 columns]


In [4]:
print(X)
print(y)

[[   0 2014]
 [   0 2021]
 [   0 2022]
 ...
 [6950 2023]
 [6969 2023]
 [6994 2023]]
[  333 18256 22685 ...   348   413   784]


### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [6]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [7]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

### Adding the second hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [9]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [11]:
# ann.compile(optimizer = 'adam', loss = 'mean_squared_error')
# ann.compile(optimizer = 'adam', loss=tf.keras.losses.MeanAbsoluteError())
ann.compile(loss = tf.keras.losses.MeanAbsoluteError(), optimizer = "adam", metrics = ["accuracy"])



### Training the ANN model on the Training set

In [12]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 500)

Epoch 1/500
132/132 [==============================] - 1s 3ms/step - loss: 6140.7266 - accuracy: 0.0000e+00
Epoch 2/500
132/132 [==============================] - 0s 4ms/step - loss: 6054.3901 - accuracy: 0.0000e+00
Epoch 3/500
132/132 [==============================] - 0s 3ms/step - loss: 6003.6904 - accuracy: 0.0000e+00
Epoch 4/500
132/132 [==============================] - 0s 3ms/step - loss: 5981.1704 - accuracy: 0.0000e+00
Epoch 5/500
132/132 [==============================] - 0s 4ms/step - loss: 5976.2417 - accuracy: 0.0000e+00
Epoch 6/500
132/132 [==============================] - 0s 3ms/step - loss: 5975.1406 - accuracy: 0.0000e+00
Epoch 7/500
132/132 [==============================] - 0s 3ms/step - loss: 5973.7720 - accuracy: 0.0000e+00
Epoch 8/500
132/132 [==============================] - 0s 3ms/step - loss: 5972.9058 - accuracy: 0.0000e+00
Epoch 9/500
132/132 [==============================] - 0s 3ms/step - loss: 5973.3013 - accuracy: 0.0000e+00
Epoch 10/500
132/132 [======

In [13]:
prddata = pd.read_csv('/content/drive/MyDrive/psahkprod_orders(2).csv')
X_prd = prddata.iloc[:].values


In [14]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)


print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

33/33 [==============================] - 0s 2ms/step
[[1187.8   189.  ]
 [2437.3  1355.  ]
 [1190.    218.  ]
 ...
 [ 921.39 3966.  ]
 [1524.19 4502.  ]
 [1550.22 1877.  ]]


### Predicting the results of the Test set

In [15]:
y_pred = ann.predict(X_prd)
np.set_printoptions(precision=2)
print(y_pred)

# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

55/55 [==============================] - 0s 7ms/step
[[1598.61]
 [ 959.38]
 [2153.15]
 ...
 [ 601.9 ]
 [ 676.43]
 [ 600.35]]


In [16]:
output = pd.DataFrame({'id_customer': X_prd[:, 0], 'invoice_year': X_prd[:, 1],'total_paid':y_pred[:, 0]})
print(output)
rames = [dataset, output]
result = pd.concat(rames)
print(result)
result.to_csv('result.csv')

      id_customer  invoice_year   total_paid
0             780          2024  1598.612549
1            1817          2024   959.381165
2             210          2024  2153.153564
3            1038          2024  1401.508301
4            1427          2024  1061.403564
...           ...           ...          ...
1737         5664          2024   682.914490
1738         6950          2024   603.082886
1739         6969          2024   601.903442
1740         3346          2024   676.432190
1741         6994          2024   600.351562

[1742 rows x 3 columns]
      id_customer  invoice_year    total_paid
0               0          2014    333.000000
1               0          2021  18256.000000
2               0          2022  22685.000000
3               0          2023  17810.000000
4               1          2016   3670.000000
...           ...           ...           ...
1737         5664          2024    682.914490
1738         6950          2024    603.082886
1739         6969    

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
